import {
    EDIT_COMMON_STYLES,
    UPLOAD_IMAGE, SELECT_IMAGE, DELETE_IMAGE,
    ADD_TEXT, SELECT_TEXT, EDIT_TEXT_STYLES, DELETE_TEXT,
    ADD_SHAPE, SELECT_SHAPE, EDIT_SHAPE_STYLES, DELETE_SHAPE
} from "./styles";

export {
    EDIT_COMMON_STYLES,
    UPLOAD_IMAGE, SELECT_IMAGE, DELETE_IMAGE,
    ADD_TEXT, SELECT_TEXT, EDIT_TEXT_STYLES, DELETE_TEXT,
    ADD_SHAPE, SELECT_SHAPE, EDIT_SHAPE_STYLES, DELETE_SHAPE
}
