import {
    EDIT_COMMON_STYLES,
    UPLOAD_IMAGE, SELECT_IMAGE, DELETE_IMAGE,
    ADD_TEXT, SELECT_TEXT, EDIT_TEXT, DELETE_TEXT,
} from "./styles";

export {
    EDIT_COMMON_STYLES,
    UPLOAD_IMAGE, SELECT_IMAGE, DELETE_IMAGE,
    ADD_TEXT, SELECT_TEXT, EDIT_TEXT, DELETE_TEXT,
}
